markdown: kramdown
baseurl: /blog
exclude: ['README.md']
permalink: pretty
name: The Animation Expat Blog
description: A blog about living abroad while working in the animation industry. Other topics include things related to animation, vfx, tech, and other random tidbits!
url: http://www.nick-st-clair.com/blog/

 
